# Generated by Django 4.0.2 on 2023-04-24 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('num', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre de la cuenta', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.CharField(help_text='etiqueta', max_length=15, primary_key=True, serialize=False)),
                ('nombre', models.CharField(help_text='Nombre para los informes', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='FiltroCuentas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.CharField(default='', max_length=10)),
                ('nombre', models.CharField(default='', max_length=50)),
                ('etiqueta', models.CharField(default='', max_length=15)),
                ('campo', models.CharField(choices=[('num', 'num'), ('nombre', 'nombre'), ('etiqueta', 'etiqueta')], default='num', max_length=10)),
                ('ascendiente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FiltroMovimientos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_inicial', models.CharField(default='', max_length=10)),
                ('fecha_final', models.CharField(default='', max_length=10)),
                ('descripcion', models.CharField(default='', max_length=200)),
                ('cuenta', models.CharField(default='', max_length=10)),
                ('asiento', models.CharField(default='', max_length=10)),
                ('etiqueta', models.CharField(default='', max_length=15)),
                ('campo', models.CharField(choices=[('num', 'num'), ('fecha', 'fecha'), ('descripcion', 'descripcion'), ('debe', 'debe'), ('haber', 'haber'), ('cuenta', 'cuenta')], default='num', max_length=15)),
                ('ascendiente', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Movimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField()),
                ('fecha', models.DateField()),
                ('descripcion', models.CharField(max_length=200)),
                ('debe', models.DecimalField(decimal_places=2, max_digits=8)),
                ('haber', models.DecimalField(decimal_places=2, max_digits=8)),
                ('cuenta', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='main.cuenta')),
            ],
        ),
        migrations.AddField(
            model_name='cuenta',
            name='etiqueta',
            field=models.ManyToManyField(help_text='Etiqueta o etiquetas para la generación de informes', to='main.Etiqueta'),
        ),
    ]
