# Generated by Django 4.0.2 on 2023-04-24 21:09

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('desc', models.CharField(max_length=150, verbose_name='Descripción')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorias',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CiudadProvincia',
            fields=[
                ('nombre', models.CharField(help_text='Ciudad - Provincia', max_length=150, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Nombres completos')),
                ('dni', models.CharField(max_length=10, unique=True, verbose_name='Número de cedula')),
                ('telefono', models.CharField(default='+593', max_length=13, unique=True, verbose_name='Número de teléfono')),
                ('address', models.CharField(max_length=150, verbose_name='Dirección')),
                ('dniA', models.ImageField(blank=True, null=True, upload_to='dniA%Y%m%d', verbose_name='DNI Anverso')),
                ('dniR', models.ImageField(blank=True, null=True, upload_to='dniR%Y%m%d', verbose_name='DNI Reverso')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.ciudadprovincia', verbose_name='Ciudad - Provincia')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('ruc', models.CharField(max_length=13, verbose_name='Ruc')),
                ('address', models.CharField(blank=True, max_length=150, null=True, verbose_name='Dirección')),
                ('mobile', models.CharField(default='+593', max_length=13, verbose_name='Teléfono Celular')),
                ('phone', models.CharField(default='+593', max_length=13, verbose_name='Teléfono Convencional')),
                ('website', models.CharField(default='https://', max_length=150, verbose_name='Website')),
                ('image', models.ImageField(blank=True, null=True, upload_to='company%Y%m%d', verbose_name='Imagen')),
            ],
            options={
                'verbose_name': 'Compañia',
                'verbose_name_plural': 'Compañias',
                'ordering': ['id'],
                'permissions': (('change_company', 'Can change Company'),),
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True, verbose_name='Nombre')),
                ('image', models.ImageField(blank=True, null=True, upload_to='product%Y%m%d', verbose_name='Imagen')),
                ('is_inventoried', models.BooleanField(default=True, verbose_name='¿Es inventariado?')),
                ('stock', models.IntegerField(default=1, verbose_name='Stock')),
                ('pvp', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de venta')),
                ('cto', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Precio de costo')),
                ('link', models.CharField(max_length=150, verbose_name='link')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.category', verbose_name='Categoría')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
            options={
                'verbose_name': 'Compra',
                'verbose_name_plural': 'Compras',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_joined', models.DateField(default=datetime.datetime.now)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total_iva', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('total', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pos.company')),
            ],
            options={
                'verbose_name': 'Venta',
                'verbose_name_plural': 'Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Tarjeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_tarjeta', models.CharField(max_length=16, unique=True, verbose_name='Número de Tarjeta')),
                ('tipTar', models.CharField(choices=[('Visa', 'VISA'), ('VisaT', 'VISA TITANIUM'), ('Matercard', 'MASTERCARD'), ('MatercardT', 'MASTERCARD TITANIUM'), ('Diners', 'DINERS'), ('Discover', 'DISCOVER'), ('American', 'AMERICAN EXPRESS')], default='Visa', max_length=10, verbose_name='Tipo Tarjeta')),
                ('bcoEmi', models.CharField(choices=[('Produbanco', 'PRODUBANCO'), ('Pichincha', 'PICHINCHA'), ('Loja', 'LOJA'), ('Pacífico', 'PACIFICO'), ('Bolivariano', 'BOLIVARIANO'), ('Guayaquil', 'GUAYAQUIL'), ('Austro', 'AUSTRO'), ('Jep', 'JEP')], default='Pichincha', max_length=20, verbose_name='Emisor')),
                ('mes_vencimiento', models.CharField(max_length=2, verbose_name='Mes de Vencimiento')),
                ('ano_vencimiento', models.CharField(max_length=4, verbose_name='Año de Vencimiento')),
                ('cod_seguridad', models.CharField(max_length=3, verbose_name='Código de Seguridad')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.client')),
            ],
            options={
                'verbose_name': 'Tarjeta',
                'verbose_name_plural': 'Tarjetas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=150, verbose_name='Razón Social')),
                ('dni', models.CharField(max_length=13, unique=True, verbose_name='RUC / Cédula')),
                ('telefono', models.CharField(default='+593', max_length=13, unique=True, verbose_name='Número de teléfono')),
                ('contacto', models.CharField(max_length=30, verbose_name='Contacto')),
                ('address', models.CharField(max_length=150, verbose_name='Dirección')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.ciudadprovincia', verbose_name='Ciudad - Provincia')),
            ],
            options={
                'verbose_name': 'Proveedor',
                'verbose_name_plural': 'Proveedores',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='SaleProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sale')),
            ],
            options={
                'verbose_name': 'Detalle de Venta',
                'verbose_name_plural': 'Detalle de Ventas',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='SalePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voucher', models.CharField(blank=True, default='0', max_length=10, null=True, unique=True, verbose_name='Voucher')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha del Voucher')),
                ('tipPago', models.CharField(choices=[('Corriente', 'CORRIENTE'), ('Diferido', 'DIFERIDO')], default='Corriente', max_length=10, verbose_name='Tipo Pago')),
                ('cuotas', models.CharField(max_length=2, verbose_name='Coutas')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Valor')),
                ('regTel', models.FileField(blank=True, null=True, upload_to='regTel%Y%m%d', verbose_name='Registro Telefónico')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.sale', verbose_name='Cliente')),
                ('tarjeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.tarjeta')),
            ],
            options={
                'verbose_name': 'Pago de Venta',
                'verbose_name_plural': 'Pago de Ventas',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='PurchaseProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('cant', models.IntegerField(default=0)),
                ('subtotal', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.product')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.purchase')),
            ],
            options={
                'verbose_name': 'Detalle de Compra',
                'verbose_name_plural': 'Detalle de Compras',
                'ordering': ['id'],
                'default_permissions': (),
            },
        ),
        migrations.CreateModel(
            name='PurchasePaid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('factura', models.CharField(blank=True, default='0', max_length=10, null=True, unique=True, verbose_name='Factura')),
                ('date_joined', models.DateField(default=datetime.datetime.now, verbose_name='Fecha de la factura')),
                ('valor', models.DecimalField(decimal_places=2, default=0.0, max_digits=9, verbose_name='Val')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.purchase', verbose_name='Número Factura')),
            ],
            options={
                'verbose_name': 'Pago de Compra',
                'verbose_name_plural': 'Pago de Compras',
                'ordering': ['id'],
            },
        ),
        migrations.AddField(
            model_name='purchase',
            name='supplier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.supplier'),
        ),
    ]
