# Generated by Django 4.0.2 on 2023-07-04 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_client_correo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='dniA',
        ),
        migrations.RemoveField(
            model_name='client',
            name='dniR',
        ),
        migrations.RemoveField(
            model_name='salepaid',
            name='tarjeta',
        ),
        migrations.AddField(
            model_name='salepaid',
            name='regPaid',
            field=models.FileField(blank=True, null=True, upload_to='regPaid%Y%m%d', verbose_name='Registro Pago'),
        ),
        migrations.AddField(
            model_name='salepaid',
            name='regWA',
            field=models.FileField(blank=True, null=True, upload_to='regWA%Y%m%d', verbose_name='Registro WhatsApp'),
        ),
        migrations.DeleteModel(
            name='Tarjeta',
        ),
    ]
